# Generated by Django 6.0.1 on 2026-01-13 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_experience_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='experience_level',
        ),
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.CharField(help_text="FontAwesome icon class (e.g., 'fas fa-code')", max_length=50),
        ),
        migrations.AlterField(
            model_name='job',
            name='location',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
